name: Publish VS Code Extension

on:
  # Publish only when a PR into main is merged
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish:
    # Ensure we only run on merged PRs (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install vsce
        run: npm install -g vsce

      - name: Package extension
        run: vsce package

      - name: Upload VSIX artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: '*.vsix'
          if-no-files-found: warn

      - name: Publish to Marketplace
        env:
          # Map your repo secret to the env var that vsce expects
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
        run: |
          # vsce reads token from VSCE_PAT; no need to pass --pat explicitly
          vsce publish